import { RegionConfig, Region, WasteCategory, Language, Achievement, LeaderboardEntry } from './types';

export const REGION_CONFIGS: { [key in Region]: RegionConfig } = {
  'USA': {
    name: 'United States',
    languages: ['en', 'es', 'zh', 'fr', 'pt'],
    binColors: {
      [WasteCategory.RECYCLABLE]: 'bg-blue-500',
      [WasteCategory.ORGANIC]: 'bg-green-600',
      [WasteCategory.GENERAL]: 'bg-gray-700',
      [WasteCategory.HAZARDOUS]: 'bg-red-600',
      [WasteCategory.E_WASTE]: 'bg-yellow-500',
      [WasteCategory.MEDICAL]: 'bg-red-800',
      [WasteCategory.NON_RECYCLABLE]: 'bg-black',
    },
  },
  'Germany': {
    name: 'Germany',
    languages: ['de', 'en', 'fr', 'ar', 'ru'],
    binColors: {
      [WasteCategory.RECYCLABLE]: 'bg-yellow-400', // Leichtverpackungen
      [WasteCategory.ORGANIC]: 'bg-green-700', // Biomüll
      [WasteCategory.GENERAL]: 'bg-gray-800', // Restmüll
      [WasteCategory.HAZARDOUS]: 'bg-orange-600', // Schadstoffe
      [WasteCategory.NON_RECYCLABLE]: 'bg-black',
    },
  },
  'Japan': {
    name: 'Japan',
    languages: ['ja', 'en', 'zh'],
    binColors: {
      [WasteCategory.RECYCLABLE]: 'bg-blue-400', // Recyclables (plastics, paper, etc.)
      [WasteCategory.ORGANIC]: 'bg-green-500', // Compostable
      [WasteCategory.GENERAL]: 'bg-gray-600', // Burnable
      [WasteCategory.NON_RECYCLABLE]: 'bg-stone-700', // Non-burnable
      [WasteCategory.HAZARDOUS]: 'bg-red-500', // Hazardous
    },
  },
  'India': {
    name: 'India',
    languages: ['en', 'hi', 'ta', 'te', 'ur', 'kn', 'ml'],
    binColors: {
      [WasteCategory.ORGANIC]: 'bg-green-600', // Wet waste
      [WasteCategory.RECYCLABLE]: 'bg-blue-500', // Dry waste
      [WasteCategory.HAZARDOUS]: 'bg-red-600',
      [WasteCategory.MEDICAL]: 'bg-red-800',
      [WasteCategory.E_WASTE]: 'bg-yellow-500',
      [WasteCategory.GENERAL]: 'bg-gray-800',
      [WasteCategory.NON_RECYCLABLE]: 'bg-black',
    },
  },
};

export const LANGUAGE_NAMES: { [key in Language]: string } = {
  en: "English",
  de: "Deutsch",
  ja: "日本語",
  hi: "हिन्दी",
  ta: "தமிழ்",
  te: "తెలుగు",
  zh: "中文",
  es: "Español",
  fr: "Français",
  ar: "العربية",
  pt: "Português",
  ru: "Русский",
  ur: "اردو",
  kn: "ಕನ್ನಡ",
  ml: "മലയാളം",
};

export const LOCALIZED_STRINGS = {
  en: {
    title: "Eco Sort",
    uploadPrompt: "Upload or snap a photo of your waste",
    uploadPhoto: "Upload Photo",
    changePhoto: "Change Photo",
    takePhoto: "Take Photo",
    snapPhoto: "Snap Photo",
    closeCamera: "Close Camera",
    classify: "Classify Waste",
    classifying: "Classifying...",
    results: "Classification Results",
    noResults: "Upload an image to see classification results.",
    error: "An error occurred during classification.",
    privacy: "Allow images to be used for research (opt-in)",
    feedbackThanks: "Thank you for your feedback!",
    language: "Language",
    region: "Region",
    yourScore: "Your Score",
    ecoJourney: "Your Eco Journey",
    leaderboard: "Leaderboard",
    achievements: "Achievements",
    achievementUnlocked: "Achievement Unlocked!",
  },
  de: {
    title: "Eco Sort",
    uploadPrompt: "Laden Sie ein Foto Ihres Abfalls hoch oder machen Sie eines",
    uploadPhoto: "Foto hochladen",
    changePhoto: "Foto ändern",
    takePhoto: "Foto machen",
    snapPhoto: "Foto aufnehmen",
    closeCamera: "Kamera schließen",
    classify: "Abfall klassifizieren",
    classifying: "Klassifizierung...",
    results: "Klassifizierungsergebnisse",
    noResults: "Laden Sie ein Bild hoch, um die Klassifizierungsergebnisse zu sehen.",
    error: "Bei der Klassifizierung ist ein Fehler aufgetreten.",
    privacy: "Bilder für Forschungszwecke zulassen (Opt-in)",
    feedbackThanks: "Vielen Dank für Ihr Feedback!",
    language: "Sprache",
    region: "Region",
    yourScore: "Ihre Punktzahl",
    ecoJourney: "Ihre Öko-Reise",
    leaderboard: "Bestenliste",
    achievements: "Erfolge",
    achievementUnlocked: "Erfolg freigeschaltet!",
  },
  ja: {
    title: "エコソート",
    uploadPrompt: "ゴミの写真をアップロードまたは撮影してください",
    uploadPhoto: "写真をアップロード",
    changePhoto: "写真を変更",
    takePhoto: "写真を撮る",
    snapPhoto: "スナップ写真",
    closeCamera: "カメラを閉じる",
    classify: "ゴミを分類する",
    classifying: "分類中...",
    results: "分類結果",
    noResults: "画像をアップロードして分類結果を表示します。",
    error: "分類中にエラーが発生しました。",
    privacy: "研究目的での画像の使用を許可する（オプトイン）",
    feedbackThanks: "ご意見ありがとうございます！",
    language: "言語",
    region: "地域",
    yourScore: "あなたのスコア",
    ecoJourney: "あなたのエコジャーニー",
    leaderboard: "リーダーボード",
    achievements: "実績",
    achievementUnlocked: "実績のロックが解除されました！",
  },
  hi: {
    title: "इको सॉर्ट",
    uploadPrompt: "अपने कचरे की तस्वीर अपलोड करें या खींचें",
    uploadPhoto: "फोटो अपलोड करें",
    changePhoto: "फोटो बदलें",
    takePhoto: "फोटो लें",
    snapPhoto: "फोटो खींचे",
    closeCamera: "कैमरा बंद करें",
    classify: "कचरे का वर्गीकरण करें",
    classifying: "वर्गीकरण हो रहा है...",
    results: "वर्गीकरण के परिणाम",
    noResults: "वर्गीकरण परिणाम देखने के लिए एक छवि अपलोड करें।",
    error: "वर्गीकरण के दौरान एक त्रुटि हुई।",
    privacy: "अनुसंधान के लिए छवियों का उपयोग करने की अनुमति दें (ऑप्ट-इन)",
    feedbackThanks: "आपकी प्रतिक्रिया के लिए धन्यवाद!",
    language: "भाषा",
    region: "क्षेत्र",
    yourScore: "आपका स्कोर",
    ecoJourney: "आपकी पर्यावरण यात्रा",
    leaderboard: "लीडरबोर्ड",
    achievements: "उपलब्धियां",
    achievementUnlocked: "उपलब्धि अनलॉक हो गई!",
  },
  ta: {
    title: "ஈக்கோ சார்ட்",
    uploadPrompt: "உங்கள் கழிவுகளின் புகைப்படத்தைப் பதிவேற்றவும் அல்லது எடுக்கவும்",
    uploadPhoto: "புகைப்படத்தைப் பதிவேற்றவும்",
    changePhoto: "புகைப்படத்தை மாற்றவும்",
    takePhoto: "புகைப்படம் எடு",
    snapPhoto: "புகைப்படம் எடு",
    closeCamera: "கேமராவை மூடு",
    classify: "கழிவுகளை வகைப்படுத்தவும்",
    classifying: "வகைப்படுத்தப்படுகிறது...",
    results: "வகைப்படுத்தல் முடிவுகள்",
    noResults: "வகைப்படுத்தல் முடிவுகளைக் காண ஒரு படத்தைப் பதிவேற்றவும்.",
    error: "வகைப்படுத்தலின் போது ஒரு பிழை ஏற்பட்டது.",
    privacy: "ஆராய்ச்சிக்கு படங்களைப் பயன்படுத்த அனுமதிக்கவும் (விருப்பத்தேர்வு)",
    feedbackThanks: "உங்கள் கருத்துக்கு நன்றி!",
    language: "மொழி",
    region: "பகுதி",
    yourScore: "உங்கள் மதிப்பெண்",
    ecoJourney: "உங்கள் சுற்றுச்சூழல் பயணம்",
    leaderboard: "முன்னிலை வகிப்பவர்கள்",
    achievements: "சாதனைகள்",
    achievementUnlocked: "சாதனை திறக்கப்பட்டது!",
  },
  te: {
    title: "ఎకో సార్ట్",
    uploadPrompt: "మీ వ్యర్థాల ఫోటోను అప్‌లోడ్ చేయండి లేదా తీయండి",
    uploadPhoto: "ఫోటోను అప్‌లోడ్ చేయండి",
    changePhoto: "ఫోటోను మార్చండి",
    takePhoto: "ఫోటో తీయండి",
    snapPhoto: "ఫోటో తీయండి",
    closeCamera: "కెమెరాను మూసివేయండి",
    classify: "వ్యర్థాలను వర్గీకరించండి",
    classifying: "వర్గీకరిస్తోంది...",
    results: "వర్గీకరణ ఫలితాలు",
    noResults: "వర్గీకరణ ఫలితాలను చూడటానికి ఒక చిత్రాన్ని అప్‌లోడ్ చేయండి.",
    error: "వర్గీకరణ సమయంలో ఒక లోపం సంభవించింది.",
    privacy: "పరిశోధన కోసం చిత్రాలను ఉపయోగించడానికి అనుమతించండి (ఆప్ట్-ఇన్)",
    feedbackThanks: "మీ అభిప్రాయానికి ధన్యవాదాలు!",
    language: "భాష",
    region: "ప్రాంతం",
    yourScore: "మీ స్కోరు",
    ecoJourney: "మీ పర్యావరణ ప్రయాణం",
    leaderboard: "లీడర్‌బోర్డ్",
    achievements: "విజయాలు",
    achievementUnlocked: "విజయం అన్‌లాక్ చేయబడింది!",
  },
  zh: {
    title: "环保分类",
    uploadPrompt: "上传或拍摄您的废物照片",
    uploadPhoto: "上传照片",
    changePhoto: "更换照片",
    takePhoto: "拍照",
    snapPhoto: "拍照",
    closeCamera: "关闭相机",
    classify: "分类废物",
    classifying: "分类中...",
    results: "分类结果",
    noResults: "上传图像以查看分类结果。",
    error: "分类过程中发生错误。",
    privacy: "允许将图像用于研究（选择加入）",
    feedbackThanks: "感谢您的反馈！",
    language: "语言",
    region: "地区",
    yourScore: "你的分数",
    ecoJourney: "您的环保之旅",
    leaderboard: "排行榜",
    achievements: "成就",
    achievementUnlocked: "成就已解锁！",
  },
  es: {
    title: "Eco Sort",
    uploadPrompt: "Sube o toma una foto de tus residuos",
    uploadPhoto: "Subir Foto",
    changePhoto: "Cambiar Foto",
    takePhoto: "Tomar Foto",
    snapPhoto: "Capturar Foto",
    closeCamera: "Cerrar Cámara",
    classify: "Clasificar Residuos",
    classifying: "Clasificando...",
    results: "Resultados de la Clasificación",
    noResults: "Sube una imagen para ver los resultados de la clasificación.",
    error: "Ocurrió un error durante la clasificación.",
    privacy: "Permitir que las imágenes se usen para investigación (opcional)",
    feedbackThanks: "¡Gracias por tus comentarios!",
    language: "Idioma",
    region: "Región",
    yourScore: "Tu Puntuación",
    ecoJourney: "Tu Viaje Ecológico",
    leaderboard: "Tabla de Clasificación",
    achievements: "Logros",
    achievementUnlocked: "¡Logro desbloqueado!",
  },
  fr: {
    title: "Eco Tri",
    uploadPrompt: "Téléchargez ou prenez une photo de vos déchets",
    uploadPhoto: "Télécharger une photo",
    changePhoto: "Changer de photo",
    takePhoto: "Prendre une photo",
    snapPhoto: "Capturer",
    closeCamera: "Fermer la caméra",
    classify: "Classifier les déchets",
    classifying: "Classification en cours...",
    results: "Résultats de la classification",
    noResults: "Téléchargez une image pour voir les résultats de la classification.",
    error: "Une erreur est survenue lors de la classification.",
    privacy: "Autoriser l'utilisation des images pour la recherche (opt-in)",
    feedbackThanks: "Merci pour votre retour !",
    language: "Langue",
    region: "Région",
    yourScore: "Votre Score",
    ecoJourney: "Votre Parcours Écologique",
    leaderboard: "Classement",
    achievements: "Succès",
    achievementUnlocked: "Succès débloqué !",
  },
  ar: {
    title: "إيكو سورت",
    uploadPrompt: "قم بتحميل أو التقاط صورة لنفاياك",
    uploadPhoto: "تحميل صورة",
    changePhoto: "تغيير الصورة",
    takePhoto: "التقط صورة",
    snapPhoto: "التقاط صورة",
    closeCamera: "إغلاق الكاميرا",
    classify: "صنف النفايات",
    classifying: "جارٍ التصنيف...",
    results: "نتائج التصنيف",
    noResults: "قم بتحميل صورة لرؤية نتائج التصنيف.",
    error: "حدث خطأ أثناء التصنيف.",
    privacy: "السماح باستخدام الصور للبحث (اختياري)",
    feedbackThanks: "شكرا لملاحظاتك!",
    language: "اللغة",
    region: "المنطقة",
    yourScore: "درجاتك",
    ecoJourney: "رحلتك البيئية",
    leaderboard: "لوحة المتصدرين",
    achievements: "الإنجازات",
    achievementUnlocked: "تم فتح الإنجاز!",
  },
  pt: {
    title: "Eco Sort",
    uploadPrompt: "Envie ou tire uma foto do seu lixo",
    uploadPhoto: "Enviar Foto",
    changePhoto: "Mudar Foto",
    takePhoto: "Tirar Foto",
    snapPhoto: "Capturar Foto",
    closeCamera: "Fechar Câmera",
    classify: "Classificar Lixo",
    classifying: "Classificando...",
    results: "Resultados da Classificação",
    noResults: "Envie uma imagem para ver os resultados da classification.",
    error: "Ocorreu um erro durante a classification.",
    privacy: "Permitir que as imagens sejam usadas para pesquisa (opcional)",
    feedbackThanks: "Obrigado pelo seu feedback!",
    language: "Idioma",
    region: "Região",
    yourScore: "Sua Pontuação",
    ecoJourney: "Sua Jornada Ecológica",
    leaderboard: "Quadro de Líderes",
    achievements: "Conquistas",
    achievementUnlocked: "Conquista desbloqueada!",
  },
  ru: {
    title: "Эко Сорт",
    uploadPrompt: "Загрузите или сделайте фото ваших отходов",
    uploadPhoto: "Загрузить фото",
    changePhoto: "Изменить фото",
    takePhoto: "Сделать фото",
    snapPhoto: "Сфотографировать",
    closeCamera: "Закрыть камеру",
    classify: "Классифицировать отходы",
    classifying: "Классификация...",
    results: "Результаты классификации",
    noResults: "Загрузите изображение, чтобы увидеть результаты классификации.",
    error: "Произошла ошибка во время классификации.",
    privacy: "Разрешить использование изображений для исследований (опционально)",
    feedbackThanks: "Спасибо за ваш отзыв!",
    language: "Язык",
    region: "Регион",
    yourScore: "Ваш счёт",
    ecoJourney: "Ваше Эко-путешествие",
    leaderboard: "Таблица лидеров",
    achievements: "Достижения",
    achievementUnlocked: "Достижение разблокировано!",
  },
  ur: {
    title: "ایکو سورٹ",
    uploadPrompt: "اپنے فضلے کی تصویر اپ لوڈ کریں یا کھینچیں",
    uploadPhoto: "تصویر اپ لوڈ کریں",
    changePhoto: "تصویر تبدیل کریں",
    takePhoto: "تصویر لیں",
    snapPhoto: "تصویر کھینچیں",
    closeCamera: "کیمرہ بند کریں",
    classify: "فضلہ کی درجہ بندی کریں",
    classifying: "درجہ بندی ہو رہی ہے...",
    results: "درجہ بندی کے نتائج",
    noResults: "درجہ بندی کے نتائج دیکھنے کے لیے ایک تصویر اپ لوڈ کریں۔",
    error: "درجہ بندی کے دوران ایک خرابی پیش آئی۔",
    privacy: "تحقیق کے لیے تصاویر استعمال کرنے کی اجازت دیں (آپٹ ان)",
    feedbackThanks: "آپ کی رائے کا شکریہ!",
    language: "زبان",
    region: "علاقہ",
    yourScore: "آپ کا سکور",
    ecoJourney: "آپ کا ایکو سفر",
    leaderboard: "لیڈر بورڈ",
    achievements: "کامیابیاں",
    achievementUnlocked: "کامیابی کھل گئی!",
  },
  kn: {
    title: "ಇಕೋ ಸಾರ್ಟ್",
    uploadPrompt: "ನಿಮ್ಮ ತ್ಯಾಜ್ಯದ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಅಥವಾ ಸ್ನ್ಯಾಪ್ ಮಾಡಿ",
    uploadPhoto: "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    changePhoto: "ಫೋಟೋ ಬದಲಾಯಿಸಿ",
    takePhoto: "ಫೋಟೋ ತೆಗೆಯಿರಿ",
    snapPhoto: "ಫೋಟೋ ತೆಗೆಯಿರಿ",
    closeCamera: "ಕ್ಯಾಮೆರಾ ಮುಚ್ಚಿ",
    classify: "ತ್ಯಾಜ್ಯವನ್ನು ವರ್ಗೀಕರಿಸಿ",
    classifying: "ವರ್ಗೀಕರಿಸಲಾಗುತ್ತಿದೆ...",
    results: "ವರ್ಗೀಕರಣ ಫಲಿತಾಂಶಗಳು",
    noResults: "ವರ್ಗೀಕರಣ ಫಲಿತಾಂಶಗಳನ್ನು ನೋಡಲು ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    error: "ವರ್ಗೀಕರಣದ ಸಮಯದಲ್ಲಿ ದೋಷ ಸಂಭವಿಸಿದೆ.",
    privacy: "ಸಂಶೋಧನೆಗಾಗಿ ಚಿತ್ರಗಳನ್ನು ಬಳಸಲು ಅನುಮತಿಸಿ (ಆಪ್ಟ್-ಇನ್)",
    feedbackThanks: "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಧನ್ಯವಾದಗಳು!",
    language: "ಭಾಷೆ",
    region: "ಪ್ರದೇಶ",
    yourScore: "ನಿಮ್ಮ ಸ್ಕೋರ್",
    ecoJourney: "ನಿಮ್ಮ ಪರಿಸರ ಪ್ರಯಾಣ",
    leaderboard: "ನಾಯಕ ಪಟ್ಟಿ",
    achievements: "ಸಾಧನೆಗಳು",
    achievementUnlocked: "ಸಾಧನೆಯನ್ನು ಅನ್ಲಾಕ್ ಮಾಡಲಾಗಿದೆ!",
  },
  ml: {
    title: "ഇക്കോ സോർട്ട്",
    uploadPrompt: "നിങ്ങളുടെ മാലിന്യത്തിന്റെ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക അല്ലെങ്കിൽ എടുക്കുക",
    uploadPhoto: "ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക",
    changePhoto: "ഫോട്ടോ മാറ്റുക",
    takePhoto: "ഫോട്ടോ എടുക്കുക",
    snapPhoto: "ഫോട്ടോ എടുക്കുക",
    closeCamera: "ക്യാമറ അടയ്ക്കുക",
    classify: "മാലിന്യം തരംതിരിക്കുക",
    classifying: "തരംതിരിക്കുന്നു...",
    results: "തരംതിരിക്കൽ ഫലങ്ങൾ",
    noResults: "തരംതിരിക്കൽ ഫലങ്ങൾ കാണാൻ ഒരു ചിത്രം അപ്‌ലോഡ് ചെയ്യുക.",
    error: "തരംതിരിക്കുമ്പോൾ ഒരു പിശക് സംഭവിച്ചു.",
    privacy: "ഗവേഷണത്തിനായി ചിത്രങ്ങൾ ഉപയോഗിക്കാൻ അനുവദിക്കുക (ഓപ്റ്റ്-ഇൻ)",
    feedbackThanks: "നിങ്ങളുടെ അഭിപ്രായത്തിന് നന്ദി!",
    language: "ഭാഷ",
    region: "പ്രദേശം",
    yourScore: "നിങ്ങളുടെ സ്കോർ",
    ecoJourney: "നിങ്ങളുടെ ഇക്കോ യാത്ര",
    leaderboard: "ലീഡർബോർഡ്",
    achievements: "നേട്ടങ്ങൾ",
    achievementUnlocked: "നേട്ടം അൺലോക്ക് ചെയ്തു!",
  },
};

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_scan',
    name: 'First Scan!',
    description: 'Classify your first item.',
    check: ({ totalClassified }) => totalClassified >= 1,
  },
  {
    id: 'rookie_sorter',
    name: 'Rookie Sorter',
    description: 'Classify 5 items.',
    check: ({ totalClassified }) => totalClassified >= 5,
  },
  {
    id: 'green_guru',
    name: 'Green Guru',
    description: 'Classify 25 items.',
    check: ({ totalClassified }) => totalClassified >= 25,
  },
  {
    id: 'recycling_champion',
    name: 'Recycling Champion',
    description: 'Classify 10 recyclable items.',
    check: ({ categoriesClassified }) => (categoriesClassified[WasteCategory.RECYCLABLE] || 0) >= 10,
  },
  {
    id: 'compost_king',
    name: 'Compost King',
    description: 'Classify 10 organic items.',
    check: ({ categoriesClassified }) => (categoriesClassified[WasteCategory.ORGANIC] || 0) >= 10,
  },
  {
    id: 'points_starter',
    name: 'Point Starter',
    description: 'Earn your first 100 points.',
    check: ({ totalScore }) => totalScore >= 100,
  },
  {
    id: 'high_scorer',
    name: 'High Scorer',
    description: 'Reach a score of 500.',
    check: ({ totalScore }) => totalScore >= 500,
  },
];

export const DUMMY_LEADERBOARD: LeaderboardEntry[] = [
    { name: 'EcoWarrior', score: 1250 },
    { name: 'GreenThumb', score: 980 },
    { name: 'RecycleRex', score: 720 },
    { name: 'PlanetProtector', score: 450 },
    { name: 'SortMaster', score: 210 },
];